language: python
python:
  - "3.6"

notifications:
  email: false

before_install:
    - sudo apt-get install libgsl0-dev
    - pip install -q numpy cython

install:
    - python setup.py install

script:
    - python tests/testing.py
