language: python
python:
  - "3.6"

notifications:
  email: false

before_install:
    - sudo apt-get install libgsl0ldbl
    - pip install -q numpy cython

install:
    - python setup.py build_ext --inplace